version: "3"
services:
  app:
#    image: lordrahl/tic_tac
    container_name: "app_backend"
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    ports:
      - 9901:80
#    volumes:
#      - ./:/var/www/html

    env_file:
      - .envs/local/.app.env
    depends_on:
      - redis
      - database

  database:
    image: mysql:5.7
    container_name: "app_database"
    ports:
      - 33064:3306
    env_file:
      - ./.envs/local/.mysql.env

  redis:
    image: redis:latest
